Adds suds to using soap, soapy water, temporary decal framework
AetherStation/AetherStation13 pull request #138
Opened 2022-08-05 12:03 UTC by kriskog

## About The Pull Request
Adds self deleting temporary decals. Supports a variety of modes, from the simplest "delete after x time" to "change icon states and alpha".
Uses this to add bubbles to soap. Cleaning with or dragging soap around will now cause it to leave behind bubbles on the floor for a little while. Adds soapy water, made by putting a soap in water. This also makes bubbles.
Fixed an ancient issue that caused water to clean as well as space cleaner in sprays, and added soapy water as a 60% to clean.
Added a clean speed modifier to the various janitorial reagents when using them with the mop. Makes it worth seeking them out.
![image](https://user-images.githubusercontent.com/33292112/183070208-4e0224fe-c980-4f08-8120-bee0e6f5724e.png)

![image](https://media.discordapp.net/attachments/653176867880173578/773364480297009192/arcane_suds.gif)

Soapy bubble sprites by @ArcaneMusic 

## Why It's Good For The Game
Adds depth

## Changelog
:cl: Skoglol
add: Soapy water, and a visual effect when cleaning with soapy water or soap. Make soapy water by putting soap in water. Water, holy water, soapy water, vodka and space cleaner now have different mopping speed, in ascending order. Soapy water can be sprayed like space cleaner, but wont always clean everythign.
add: Temporary decals framework.
fix: Water no longer cleans floors when sprayed. 
/:cl:

2022-08-06 18:01 UTC, stanalbatross requested changes

2022-08-06 18:01 UTC, stanalbatross commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	if(prob(60)) //Worse than space cleaner
duping this prob(60) makes it seem like the `60` should be made into a var

2022-08-06 18:01 UTC, stanalbatross commented on code/modules/reagents/reagent_containers/glass.dm
> +			reagents.trans_to(M, 5, transfered_by = user)
as above

2022-08-09 20:51 UTC, kriskog commented
Thanks 👍

2022-08-10 08:54 UTC, merged