Reworks heretic curses
AetherStation/AetherStation13 pull request #185
Opened 2022-08-13 09:08 UTC by SuperSlayer0

## About The Pull Request

Port of https://github.com/The-Merchants-Guild/Merchant-Station-13/pull/286

Instead of cursing one person that touched an item, heretics now curse an item to apply the effect to the non heretic that touches said item.

## Why It's Good For The Game

Makes heretic curses usefull and not suck 

## Changelog
:cl: eeSPee, ported by SuperSlayer
balance: Heretics curses now curse items instead of a person who touched them, making the items apply the curse effects on pickup
/:cl:

2022-08-15 07:21 UTC, Canohaaaaaaa requested changes

2022-08-15 07:21 UTC, Canohaaaaaaa commented on code/datums/elements/eldritch_curse.dm
> +	src.duration = nduration
```suggestion
/datum/element/eldritch_curse/Attach(datum/target, duration, datum/callback/curse, datum/callback/uncurse)
	. = ..()
	if(!isitem(target))
		return ELEMENT_INCOMPATIBLE

	src.duration = duration
```

2022-08-15 07:21 UTC, Canohaaaaaaa commented on code/datums/elements/eldritch_curse.dm
> +	src.Detach(source)
```suggestion
	Detach(source)
```

2022-08-29 11:57 UTC, EdgeLordExe commented
I don't believe this fits our servers

2022-08-29 11:57 UTC, closed without merging