Economy reverts
AetherStation/AetherStation13 pull request #188
Opened 2022-08-13 10:21 UTC by kriskog

## About The Pull Request
Economy is not in a good place, at least for our environment.
Added back wages - reduced starting cash, you'll reach the old starting level at 10 minutes.
Department budgets still static income, but increased this to ensure no department goes broke due to wages. Depending on amount of assistants, civilian budget might be in trouble. Ideally this would be a variable number, but for now go rob some of your fellow assistants if your wages stop coming in.
Inflation is gone, market crash event is gone too as it used the inflation systems.
Job equipment is free within your own department again. Premium and hacked items still have a cost.
Mail holidays are gone, no sunday break for the CTs.

Reminder to turn off payday notifications in preferences.

## Why It's Good For The Game
Let the wealth flow

## Changelog
:cl: Skog
balance: Large changes to economy. Wages are back, inflation is gone, job tools are free, mail arrives on sundays and holidays.
/:cl:

2022-08-13 10:24 UTC, Pugie commented
This breaks economy 🤓

2022-08-15 07:29 UTC, Canohaaaaaaa requested changes
Didn't put the shotgun or pulse buff in the changelog and also why did you buff shotguns overall while adding back the most powerful ammo for it.

2022-08-15 07:30 UTC, Canohaaaaaaa approved these changes

2022-08-15 07:30 UTC, Canohaaaaaaa commented
Wrong pr

2022-08-16 13:57 UTC, merged