Adding a SciLock feature to Nanite Cloud Controllers and refining circuitboard code
AetherStation/AetherStation13 pull request #263
Opened 2022-08-24 23:42 UTC by PolishUser

## About The Pull Request

This PR is going to add a brand new feature from the NT for nanite cloud controllers called the SciLock. This feature will require crewmembers' IDs to have RnD access to log into a nanite cloud controller. This feature may be disabled with a use of multitool on a borad or hacked with a use of cryptographic sequnecer on a board or the machine itself.

This PR also will improve some circutboard.dm code.

## Why It's Good For The Game

It prevents non-antags from griefing while not gatekeeping nanites to a single department. In addition, there will be another use for the cryptographic sequencer.

Also, some code improvements.

## Changelog
:cl:
add: Added SciLock for Nanite Cloud Controllers
code: Improved configure_machine proc in circuitboard.dm
/:cl:

2022-08-24 23:56 UTC, Sparkezel commented
Good work my man, keep it up!

2022-08-26 13:20 UTC, Pugie commented
> Uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
> 
> Consider:
> 
> They can still deconstruct the nanite controller, causing the nanites to lose sync, causing people to die anyway. While this prevents uploading, this still doesn't stop the most malicious form of sabotage which is to simply break the controller.
> 
> It's a good change, I'll admit - but 90% of malicious programs uploaded to the cloud come from sci, and the most common form of sabotage is just to break it.

That's life!

2022-08-28 11:54 UTC, Canohaaaaaaa requested changes

2022-08-28 11:54 UTC, Canohaaaaaaa commented on code/game/objects/items/circuitboards/computer_circuitboards.dm
> +	var/scienceLock = TRUE
```snake_case```

2022-08-28 11:54 UTC, Canohaaaaaaa commented on code/modules/research/nanites/nanite_cloud_controller.dm
> +	var/scienceLock = TRUE
ditto

2022-08-28 11:54 UTC, Canohaaaaaaa commented on code/modules/research/nanites/nanite_cloud_controller.dm
> +	data["sciLock"] = scienceLock
ditto

2022-09-02 17:27 UTC, merged