SecHUD markers
AetherStation/AetherStation13 pull request #69
Opened 2022-07-08 19:33 UTC by TheChosenEvilOne

## About The Pull Request
Adds markers you can create when wearing SecHUD glasses, only visible to other people with SecHUD.
ctrl+mmb makes an alert marker and alt+mmb makes a question marker.

## Why It's Good For The Game
Makes it easier for sec to coordinate quickly.

## Changelog
:cl:
add: When wearing SecHUD glasses you can now create markers with ctrl + MMB (alert marker) and alt + MMB (question marker).
/:cl:

2022-07-08 20:56 UTC, Pugie commented
toxic LoL PR

2022-07-09 09:14 UTC, TheChosenEvilOne commented
> toxic LoL PR

yes

2022-07-09 10:20 UTC, EdgeLordExe commented
add a sound alert that plays to nearby sechud users when placing/removing a marker

2022-07-09 15:38 UTC, TheChosenEvilOne commented
> add a sound alert that plays to nearby sechud users when placing/removing a marker

I have been thinking about it for a bit, and the only reasonable way of playing audio I can think of is by checking the distance to every person wearing sechud. I guess Ill have to look into doing that.

2022-07-11 17:39 UTC, Canohaaaaaaa requested changes

2022-07-11 17:39 UTC, Canohaaaaaaa commented on code/modules/clothing/glasses/hud.dm
> +/obj/item/clothing/glasses/hud/security/proc/create_ping(datum/source, atom/A, params)
`SIGNAL_HANDLER`

2022-07-11 17:39 UTC, Canohaaaaaaa commented on code/modules/clothing/glasses/hud.dm
> +	var/mob/living/L = source
Descriptive var name

2022-07-21 16:31 UTC, merged