Removes knockdown from stunbaton and all its children
AetherStation/AetherStation13 pull request #84
Opened 2022-07-14 22:03 UTC by Sparkezel

## About The Pull Request
Removes knockdown from stunbatons and its children (stunprod, teleprod)
Abductor's baton and telebaton are unchanged

## Why It's Good For The Game
The stunbatons are too strong and I have hosts blessing in this regard

## Changelog
🆑
balance: Stunbatons, stunprods and teleprods no longer cause knockdown.
/🆑

2022-07-14 23:00 UTC, Burgermancoding commented
How do you get someone horizontal to arrest them

2022-07-14 23:03 UTC, Canohaaaaaaa requested changes
Use the proper PR template please.

2022-07-14 23:46 UTC, Sparkezel commented
got it, give me a moment

2022-07-15 07:26 UTC, Pugie commented
What about pump up and ephedrine? They have unique effects to counteract baton knockdown shouldn't they be altered/removed

2022-07-15 13:49 UTC, Canohaaaaaaa commented
How are you supposed to arrest someone ?

2022-07-15 15:37 UTC, Canohaaaaaaa commented
> Just click them twice bozo

This is just to lead to sec going for lethal 100% of the times when dealing with antags, and makes the baton overall much worse in team fights

2022-07-16 23:38 UTC, Naloacisamazing commented
> This is just going to lead to sec going for lethal 100% of the times when dealing with antags, and makes the baton overall much worse in team fights, I would rather we keep a good status effect to help the follow-up. Like a massive slow perhaps.

I wouldnt recommend a slow, that would just have the same issue I have with the knockdown

2022-08-03 15:53 UTC, Pugie commented
Stale bread

2022-08-04 14:49 UTC, kriskog commented
just pump up lol

2022-08-12 00:29 UTC, closed without merging

2022-08-12 08:17 UTC, exymian commented
Lwt me give a better reasoning;
Batons knockdown is a guarantee for a second stun since you are so slow and on the ground its inevitable for you to get stamcritted. There is a bigger issue that better players can do which is to shove knocked down people for a shove stun that huarantees the second baton hit. 

Currently nothing helps shorten the stamcrot since its not considered a stun. Knockdown is the only thing thats considered a stun which adrenaline and ephedrine shorten the time of.


Baton is the best weapon ever. You would keep it in your bag if you are any antag, hell even nukies go for it sometimes because its too strong. There is no counterplay potential after getting hit once.

Hence why knockdown removal is great since a person with a desword can still fight back if he gets batonned once. There is nothing that helps against a stamcrit(other than being immune to stam damage) which makes this nerf fine.

Merchant removed the knockdown and sec weren't having a bad time at all. I recommend removing the knockdown from the telebaton aswell since that is the mainly problematic and the better baton and i dont see why head of staff should have this giant advantage

2022-08-12 08:33 UTC, Canohaaaaaaa commented
Same stuff as #160, make stun resistance give something meaningful for overall stam damage and not just batons, then we can see to remove the knockdown. Don't half ass it and leave us with a useless broken trait.
You could for instance give it a %stam protection so batons take 3 hits to take you down instead of 2. In short make pump up more useful overall.